[tool.poetry]
name = "namepy"
version = "0.1.0"
description = ""
authors = ["antlet <antlet@allegheny.edu>"]
readme = "README.md"
packages = [{include = "namepy"}]

[tool.poetry.dependencies]
python = "^3.9"
typer = "^0.4"
libcst = "^0.4"
pylint = "^2.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
