name: Lint and Test

on: [push, pull_request]

jobs:
  lint:
    name: Run NamePy
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python 3.9.6
        uses: actions/setup-python@v2
        id: setup-python
        with:
          python-version: 3.9.6
      - name: Setup poetry
        uses: Gr1N/setup-poetry@v7
      - name: Install dependencies
        run: poetry install
      - name: Install spacy en_core_web_sm
        run: poetry run python -m spacy download en_core_web_sm
      - name: Run NamePy
        run: poetry run python namepy/visitor.py namepy/visitor.py
