name: Lint and Test

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python 3.9.6
        uses: actions/setup-python@v2
        id: setup-python
        with:
          python-version: 3.9.6
        # env:
        #   AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
      - name: Setup poetry
        uses: Gr1N/setup-poetry@v7
      - name: Install dependencies
        run: poetry install
      - name: Run NamePy
        run: poetry run namepy id-length test_files/basic_files/test_file.py
      - name: Run pylint
        if: always()
        run: poetry run task pylint

  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        id: setup-python
        with:
          python-version: 3.9.6
        # env:
        #   AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
      - name: Setup poetry
        uses: Gr1N/setup-poetry@v7
      - name: Install dependencies
        run: poetry install
      - name: Run test suite
        if: always()
        run: poetry run task test
